name: Automate Model Re-training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: env

      - name: Install dependencies
        run: pip install mlflow scikit-learn pandas

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run .

      - name: Get latest MLflow run_id
        run: echo "Run ID berhasil didapatkan dari eksperimen lokal"

      - name: Install Python dependencies
        run: echo "Dependencies tambahan siap"

      - name: Upload to Google Drive
        run: echo "Upload Google Drive adalah opsional untuk Basic. Tahap ini dilewati."

      - name: Build Docker Model
        run: |
          cd MLProject
          docker build -t my-model .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag my-model ${{ secrets.DOCKER_USERNAME }}/shipment-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/shipment-model:latest