name: Automate Model Re-training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: env

      - name: Install dependencies
        run: pip install mlflow scikit-learn pandas

      - name: Run mlflow project
        run: |
          # Menyalakan server MLflow di latar belakang
          mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5
          
          # Menyinkronkan perintah luar agar pakai server yang sama
          export MLFLOW_TRACKING_URI=http://127.0.0.1:5000
          
          # Menjalankan project Anda
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: echo "Run ID berhasil didapatkan"